# Generated by Django 3.2.5 on 2021-07-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='count',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
